version: '3'
services:
    php-apache:
        build:
            context: ./php
        ports:
            - 80:80
        volumes:
            - ./public_html:/var/www/html:z
        links:
            - 'mariadb'

    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Africa/Cairo"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'pass'
            MYSQL_DATABASE: 'db'

volumes:
    mariadb: